# Generated by Django 4.1.6 on 2023-02-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ietm',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='api.item'),
        ),
    ]
