# Generated by Django 4.1.6 on 2023-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, to='api.discount'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, null=True, to='api.tax'),
        ),
    ]
