# Generated by Django 4.1.6 on 2023-02-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_discount_tax_item_discount_item_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
