# Generated by Django 4.1.6 on 2023-02-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_discount_discount_alter_tax_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_id',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
