# Generated by Django 4.1.6 on 2023-02-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, to='api.discount'),
        ),
    ]
