# Generated by Django 4.1.6 on 2023-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_item_discount_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_id',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
